### ISSUE TITLE
environment.yml file is not in the bird detector repo. 

### ISSUE THREAD

**Issue by marireeves** [weecology/BirdDetector#2]
I went and cloned DeepForest repo and installed from there, but wanted to confirm it's the correct one and flag this as an issue for you. Thanks, Ben!

**Comment by bw4sz** [comment]
added. https://github.com/weecology/BirdDetector/blob/main/deepforest_config.yml

**Comment by marireeves** [comment]
You should change the setup instructions on the readme to reflect the different filename=deepforest_config.yml
