### ISSUE TITLE
bird orthomosaics

### ISSUE THREAD

**Issue by sergewich** [weecology/BirdDetector#6]
Hi Ben,
Is there a way to use an ortho instead of single images as input to the bird model? It would be so cool if that was an option and so useful. Is the bird model planned to be in ArcGIS Pro like deep forest so that we can use it there on orthos?
Best,
Serge

**Comment by ethanwhite** [comment]
This is best discussed over in the DeepForest repo. I'll respond to your question at https://github.com/weecology/DeepForest/discussions/616 shortly
